services:
  frontend:
    image: cms-frontend
    container_name: cms-frontend
    build: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    image: cms-backend
    container_name: cms-backend
    build: ./backend
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=testdb
    volumes:
      - ./backend:/app

  # db:
  #   image: mysql:8
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: testdb
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db-data:/var/lib/mysql

# volumes:
#   db-data:
