"""video

Revision ID: 87378a4a1454
Revises: d61229fc3911
Create Date: 2025-02-26 13:50:05.741878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87378a4a1454'
down_revision = 'd61229fc3911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('video')

    # ### end Alembic commands ###
